version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 898843348400.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - mvn install -DskipTests
      - docker-compose build
  post_build:
    commands:
      - docker-compose push
      - printf '[{"name":"multi-service-sample-app","imageUri":"%s"}]' ${REPOSITORY_URI}/payment-api-container-ecr:latest > images.json
      - printenv
      - cat images.json
      - echo Build completed on `date`
artifacts:
  files:
#    - payment-api-service/target/acme-poc-payment-api-service-0.0.1-SNAPSHOT.jar
#    - plan-service/target/acme-poc-plan-service-0.0.1-SNAPSHOT.jar
#    - process-service/target/acme-poc-process-service-0.0.1-SNAPSHOT.jar
    - images.json
